### ISSUE TITLE
PHP Warning index not found

### ISSUE THREAD

**Issue by enginydigital** [cbmarc/EAN128-4php#2] opened 2015-07-23 08:24 UTC
at line 136 of file EAN128-4php.php there is this code:
$checksum = $checksum % 103;
$barcode_data .= $code128c_codes[str_pad($checksum, 2, '0', STR_PAD_LEFT)];
The result of the checksum can be a value between 0 and 103 but in the array $code128c_codes only there are 99 positions. 
I think than one solution would be modify the number of mod operation and change 103 for 99. 
$checksum = $checksum % 99;
With these changes the warning disappears but this is correct?
Thanks!

**Comment by cbmarc** [comment] 2015-09-14 13:29
Hi, 

First of all, thank you for submiting an issue. I'm going to look into it as soon as possible and come back to you. 

Regards

**Comment by cbmarc** [comment] 2015-09-14 18:09
After a quick glance, the checksum % 103 has nothing to do with the problem. In addition to this, the code128c codes array has a length of 106, not 99. 

The mod 103 calculation is ok and is based on this documentation http://www.barcodeisland.com/code128.phtml.

I can't seem to reproduce the problem you say. Could you provide more info of your system / configuration? Or maybe, the way you are using the library? Here is an example of a working link on my local machine: http://localhost/EAN128-4php/EAN128-4php.php?barcode=9050758902883000000002040089620120000000076070

Using barcode: 9050758902883000000002040089620120000000076070

Is the barcode you use EAN128C? Maybe the problem is I should check the input barcode to avoid this problems. Please, provide the barcode you are trying to use.

**Comment by enginydigital** [comment] 2015-09-15 08:46
Thanks for the reply.
Yes , I use the barcode EAN128C.

You're right but the last six positions of the array $code128c_codes does not have a numeric index and if the final value of the checksum is 100 , 101 , 102 execution generates a notice to undefined index.

For example:
barcode=9050758183411411000000000290015091500000000010
PHP result -> Notice: Undefined index: 100 in /EAN128-4php/EAN128-4php.php on line 137 
In this example the value of these lines are the following:
$checksum = 7310 % 103;
$cheksum = 100;

**Comment by cbmarc** [comment] 2015-09-15 09:28
Oh, ok. Sorry for that. I think I have the problem.

Let me look at it later and I will come back to you (hopefully) with a soluton =)

**Comment by cbmarc** [comment] 2015-09-15 15:23
Probably fixed the issue. But still have to test it further. You can check though.

**Comment by cbmarc** [comment] 2015-09-15 19:06
Current commit could be wrong so take it cautiously. Should you solve it please tell me. For today I must leave.

**Comment by cbmarc** [comment] 2015-09-16 13:59
Hi, 
As per my last commit, problem is now solved.
Some mappings where missing in the EAN128C mapping file. That caused the problem.

Tested it with you barcode and it's working. If you can confirm it's solved within 5 days I will close the issue, after that I will close it anyway.

Thank you again for reporting the issue.

**Comment by enginydigital** [comment] 2015-09-16 14:05
The latest modification doesn't work. Try it with the code 9050758183411411000000000100016091500000000010.

Anyway I think I have a solution to the issue. In the previous version to the latest modification, change the line 136 ($barcode_data .= $code128c_codes[str_pad($checksum, 2, '0', STR_PAD_LEFT)];) for these other lines:

$code_keys = array_keys($code128c_codes);
$barcode_data .= $code128c_codes[$code_keys[$checksum]];

Firstly I get the position vector and then after I get the value of this key.

Let me know what you think ;)

**Comment by cbmarc** [comment] 2015-09-16 14:13
Although I must say the latest modification (13 minutes ago) works for me even with your latest barcode, I find your solution cleaner, so I'm going to implement that.

Thanks.

**Closed as completed** 2015-09-16 14:19 UTC
